jwt:
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  secret: ${JWT_SECRET}

spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

springdoc:
  swagger-ui:
    urls:
      - name: Auction
        url: /swagger/auction-service
      - name: Deposit
        url: /swagger/deposit-service
      - name: Product
        url: /swagger/product-service
      - name: Search
        url: /swagger/search-service
      - name: Settlement
        url: /swagger/settlement-service
      - name: User
        url: /swagger/user-service
      - name: File
        url: /swagger/file-service